-- Copyright (c) General Electric Company, 2017.  All rights reserved.

-- noinspection SqlDialectInspectionForFile

-- noinspection SqlNoDataSourceInspectionForFile

--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.31.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/8/2016 3:23:58 PM
-- Server version: 5.7.16
-- Client version: 4.1
--


--
-- Definition for database rt106db
--
CREATE DATABASE IF NOT EXISTS rt106db
	CHARACTER SET latin1
	COLLATE latin1_general_ci;

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE rt106db;

--
-- Definition for table execution_log
--
CREATE TABLE IF NOT EXISTS execution_log (
  ID BIGINT(20) NOT NULL AUTO_INCREMENT,
  start_time VARCHAR(255) DEFAULT NULL,
  end_time VARCHAR(255) DEFAULT NULL,
  user VARCHAR(255) NOT NULL,
  protocol_version VARCHAR(255) NOT NULL DEFAULT '1.0',
  message_type ENUM('request','response','execution') NOT NULL,
  message_header JSON DEFAULT NULL,
  message_json JSON NOT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 76
AVG_ROW_LENGTH = 1394
CHARACTER SET latin1
COLLATE latin1_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS analytic_evaluation (
  ID bigint(20) NOT NULL AUTO_INCREMENT,
  executionId varchar(255) DEFAULT NULL,
  user_evaluation varchar(255) DEFAULT NULL,
  user_comments varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_general_ci
ROW_FORMAT = DYNAMIC;

CREATE TABLE IF NOT EXISTS client_info (
  client_name varchar(255) NOT NULL,
  responses_expected int(11) UNSIGNED DEFAULT 0,
  last_touched bigint(20) UNSIGNED DEFAULT 0,
  PRIMARY KEY (client_name)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_general_ci
ROW_FORMAT = DYNAMIC;


CREATE TABLE IF NOT EXISTS service_health (
  name varchar(50) NOT NULL,
  URL varchar(255) NOT NULL,
  type varchar(255) DEFAULT NULL,
  last_checked bigint(20) UNSIGNED DEFAULT NULL,
  status_code int(11) UNSIGNED DEFAULT NULL,
  status_string varchar(255) DEFAULT NULL,
  PRIMARY KEY (name)
)
ENGINE = INNODB
AVG_ROW_LENGTH = 2730
CHARACTER SET latin1
COLLATE latin1_general_ci
ROW_FORMAT = DYNAMIC;

INSERT IGNORE service_health(name, URL, type) VALUES
('DataStore', 'http://datastore:5106/v1/health', 'core');




--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
